fn sum(input: Vec<char>) {
    let mut sum = 0;
    for value in input {
        match value {
            'a' => sum += 1,
            'b' => sum += 2,
            'c' => sum += 3,
            'd' => sum += 4,
            'e' => sum += 5,
            'f' => sum += 6,
            'g' => sum += 7,
            'h' => sum += 8,
            'i' => sum += 9,
            'j' => sum += 10,
            'k' => sum += 11,
            'l' => sum += 12,
            'm' => sum += 13,
            'n' => sum += 14,
            'o' => sum += 15,
            'p' => sum += 16,
            'q' => sum += 17,
            'r' => sum += 18,
            's' => sum += 19,
            't' => sum += 20,
            'u' => sum += 21,
            'v' => sum += 22,
            'w' => sum += 23,
            'x' => sum += 24,
            'y' => sum += 25,
            'z' => sum += 26,
            'A' => sum += 27,
            'B' => sum += 28,
            'C' => sum += 29,
            'D' => sum += 30,
            'E' => sum += 31,
            'F' => sum += 32,
            'G' => sum += 33,
            'H' => sum += 34,
            'I' => sum += 35,
            'J' => sum += 36,
            'K' => sum += 37,
            'L' => sum += 38,
            'M' => sum += 39,
            'N' => sum += 40,
            'O' => sum += 41,
            'P' => sum += 42,
            'Q' => sum += 43,
            'R' => sum += 44,
            'S' => sum += 45,
            'T' => sum += 46,
            'U' => sum += 47,
            'V' => sum += 48,
            'W' => sum += 49,
            'X' => sum += 50,
            'Y' => sum += 51,
            'Z' => sum += 52,
            x => println!("shit: {:?}", x),
        };
    }
    println!("sum: {}", sum);
}

fn task1(input: &[&str; 300]) {
    let mut common: Vec<char> = Vec::new();
    for i in input {
        let (first, second) = i.split_at(i.len() / 2);
        for char in first.chars() {
            if second.contains(char) {
                common.push(char);
                break;
            }
        }
    }
    sum(common);
}

fn task2(input: &[&str; 300]) {
    let mut group: Vec<char> = Vec::new();
    for i in (0..300).step_by(3) {
        for char in input[i].chars() {
            if input[i + 1].contains(char) {
                if input[i + 2].contains(char) {
                    group.push(char);
                    break;
                }
            }
        }
    }
    sum(group);
}

pub fn tasks() {
    let input = [
        "gfWpjRRQffQGCHHJsGqjsj",
        "SclzJZZvmmnPbJtVSqqNBqVCBdSCsd",
        "tlbvZJDZtmtPcJmlPnhMFQWWpMRFTfLDRRTWRp",
        "HjMPgSWjVrjgbHRRSSMRgjRdpdbGdlcdCvQfcCdlwQJfdf",
        "LNDnhtNtLNFFZDtFnhzvdldDflvvDCdlJfldpJ",
        "ZFLFZZmFtFtTNTSPRrVPWWMpRP",
        "qLBSBLRwmgzqCbzCffDlrfCV",
        "TFFFHNWFMFFMpHpGHMTHGNhrldWZCsdZsslZlZfrflDVss",
        "PTMcPGntTThHhTGctnMvSwjjvmmqLBmnjqqgCR",
        "nClJtMwwntqVVPJcgZqq",
        "mjpsDcrcSSFFPZqFBWWgVP",
        "vQcjsvhrvvrmhbmNHMNnlHbNMtCtNM",
        "bgvvhnTQtjrrrhsDDf",
        "pLSMltLzLLSjFrSSjrSJHD",
        "zNWRLBdZPllPQtCvttgCqb",
        "DRlDrrFTNDNlgzsGTBfcnqhhcnJfcrCSqc",
        "MMmmdWtdLmvtldHjMmQfPBqSJWnfCCCqcWSSPJ",
        "vjHMjLmjpLtHptQLmHvwTRgNVVpTzZFZgZRlsVTN",
        "rzpMpDCGFCFFjRFsRPFRNFPv",
        "fWclbHCHtSmfvjnmfsvZ",
        "wTcTlSwwtQtWclBQBLGMLMCLVzVLwJGqLd",
        "MQSjLNjPPLLSBPjfQhSPHjDVCjDtVVpDHwbwVpbD",
        "RcmWzsRrzZrmTszWRqWlmRJscbtHwCbndCtcDVddDpdnVnbt",
        "JTsrGGTqmwTlWmTzJzWmhhPLLGgPFgBffSSPhFFM",
        "qMMRNZMDDNWLPqfzCgDcGncVDCgG",
        "wwBFhwhhBgmcVzhghG",
        "tbJbjjtJvwtdtwjpFtlbvtdTLNSMqNqMMgqNHPlZRTNggL",
        "qmjMHsZmZSbjbZMjSLFFFFwgsgvFswpwww",
        "hRJBhmnhhvFFwhcv",
        "llfWDWzrzBNTRfNBrWzzTmZbGTMjPqMmZPjVbSZGSP",
        "CRRPLwwcclcGVppQ",
        "SHFjDjjHDTfSDNTTHfSHjQVGrpmllQQWltVVVZGp",
        "HFlqzDTfqlzwbgPJLwCP",
        "WRCNLphpLppSCWVHNfLRzVnQMnBnMddPMQDFQgrhPQFM",
        "jTjJqvqjvPVJFJFBJF",
        "qTsZbvGqqZlstsmZVljtwqwSHHNWczHSSRcWNSRHzzNfbW",
        "glgzDzHjSrVHcVgbrjmNsscNGmNWssGNNtst",
        "hHPQLHJpwdLpdHfQQtnZmNMwnZGZWwsFZM",
        "QpdhPJRTJfPphJfhCBlVqVvgvVDBbvVqDbHD",
        "VtHzjZpjVtHrprgGmjHsGHNdSJFQRcLJqCdQcSqJNpcq",
        "bBWfTPwhbfDlMnhffRwQJQNdqJcLFQLSdR",
        "bhBhvfMWTnlDnTBfPSmvmjsjmmGtzHtsHm",
        "pcRPRPWrSDcJGZSStmwZZS",
        "VnLfCfTlfVzfnMMBCqVNZJdtjNtJjhJdGNNbwT",
        "BLvqCCMVsnRQsPQgDcZH",
        "cQbqqQhDGhlQfQlhQrqGsTNgLgCpRgLTPPPLNbpg",
        "wtHVddVFwSHznZwwznCpRBdjppNBNTTdCjRR",
        "ZtWFwWtSmvVnwZDrCMGfQlDDJQmD",
        "PzPZGCZzrZrlhdjdCqfCsqQdRD",
        "cbvZLVVFvbbNSNFHSDnsDQdnfqNQDRngsR",
        "FJHSLSFSScJJbWHFmFVFSZmrrzBmhtBwmzBMPMPzPh",
        "nlpFcLBgcVcLbssGVBGGrlpGPhJJJJJqPBZPDNMQMJJhJQZZ",
        "SSTjHzfHwtZSPVQVQMRQ",
        "TzVHwWfTtzwdVzsbFnGgsbdcGrLc",
        "FppVBRVZDdLmrDGmmfrQ",
        "NtNMPNshJCzznLGJSrqRrRrr",
        "tRssthhPlCWhPzsWtzhzCbVVjwTpVwdZZTpwjbdBbwBc",
        "TTWblHWScvPCCHTWFzSrqqsNNSmdmqrrpz",
        "RLRwjjnjZNprzmmZcq",
        "QQgtQnccQDGjgLDRRcLthQhFBvCbMtMHTWlBFllBbFCMTW",
        "WnBVNvDnVsNvZWdrWDLVDMbsHpTjpHCSSClsbSCCMH",
        "GPFtmztzgPhRFtJTdbTwjppSCjpgSl",
        "hJcfPtQhdtWNVZqNnqNQ",
        "GLcqZPPsnqQcFsmBBrqRvrddNqrC",
        "MtHthJwLllwvjRvvtrvBRS",
        "VHMfDLbpfznszZQG",
        "WBSdPlQPRfBtGQPfBGPBJgzgjwsJzsszJwCrdwCT",
        "ZpppVpMVpnVHMVVbZRJrCgwRzTJrwNJw",
        "MvhmnpLqLmhVmBlftRQBFSlR",
        "hhQlSJqhtCSnqZJnqShSlNDwRzpvdwRlMBMMdcjRjMpMRc",
        "frrGmLmWbfFrsmFHmBzBvBcwdJbvpjzbMM",
        "mmgFrVGLWJLFGsgfhSVtVPqntqnnSStN",
        "SFJTJTSqswwFQbwf",
        "cDtcWPclrtPwVsfssQmN",
        "HDtwWCgWdggdzSGJMSzGMq",
        "JpqJtWRJMhCMJpMQCWtFrjgHdgdlgllwNjlQjldH",
        "fBzPZcZvnBmDnZvZBZDmPvglVVVdgHHSwrNRgVgwNPRH",
        "GbZnZccfvcsZmccsmnnZTRbCCMWFTWJqFCCMJFRT",
        "vrrFqrFTBTmLmNrLMqMTHddJbHpWnhdWdWbHhJGM",
        "wBzfwzcQSzWSSshpdWGp",
        "gwjPPPDQtzQlzQDPqTgLBRmRqZBvqFNR",
        "bWVptFFsbPcZsGLhsZGmLB",
        "qnWrnrHdMCDCNqfWmvRRZSSRLdRGZGRG",
        "nNqqNDfMrMWHDQNHzWfHNDnwzblpzFlbwtFbVVlwVcPJpP",
        "BHJhlHdJQggvddglJBBhglhQzZHPZpFFPDMzFDDRDFZZDFZD",
        "rSTfqnCffMfCVfCLNqbzbjWNDbbWDPFpPFbP",
        "nfnnrSfCTVSwrqSLCGfTGlgQhlvsGMJQJBhhssJhGc",
        "tBjjDjjqfDjLfJlrLgglvmrlmrcc",
        "TwNNTVhwwpgvGSNNSssS",
        "TbwhnvvChhbVRTPPRJBJQQfJttMQQJCQfW",
        "mWSvSQVgmWQsQvspQJlrlLnJLLpCClhhlp",
        "bFHRjZdNjjBZzFzhtnCllCcJLrCBll",
        "HFFNHbdZZLZjfPFjHVQmWDDVsvsmTqVqDf",
        "JJPllQQClqgBCgdHwHbpjVTwHd",
        "tmGZtjGjHZpVbfMT",
        "ShGjNGWmDSNcNRtGmshDRzzCvzQJJRBLrvlrBPJv",
        "cTpqsTWqVVpsNLfvCDFlMFDVFL",
        "JnndJPddQgzHlvMJFDhLCG",
        "BjtntgdRnQgzjdBRQBlpNWrTTlNTSwNpWS",
        "qHmqLVLjmVqsDBLtmjmbtPwCTwwPzGWRgGwGwMwW",
        "ZhcCNCSprRTWTwSnWW",
        "hflhZvvQhppZfcNpvrhpQHjVjLmbVmmVHVCFDvqVFb",
        "nnNrwDnZrspwDNnZsNSDsNbCmpjvMTPQjLMmPmmQPGBTQP",
        "FdVtRdRfctBQPmTtTLQB",
        "qhzWVWJqVHwbhlLSsS",
        "htWmhDhFztnztDhtBmBtghPRSrpfjVwPdfPwpwnRSVrr",
        "cbCHvgJGcTqbqcbqqqcqsMsRVrSCwffdRPPpVpwCRSwfjj",
        "GlgGQqTqbgQzttmBNNFz",
        "NWQNQgdTgjQNddTZfrCQWRDnnnbqnLqnRcjJlqqvDj",
        "FtSSmSmJhpllcclDvpln",
        "JBVVSsSFBVBttShFGSPQfCGNdrMfZZTQTZNNdC",
        "HgHthMhphcbfbMMfHhsGGDCRRVlcVSScsCRz",
        "nWvPFqLqPNdjnNLnjdJnPdWjGlssDPSsllVCRzlTCTGlSDzS",
        "RvddJRJQHwQwpZZb",
        "gdZwgpjZZQtHTdrWrwdpWRnlhNBRlLbFthNhflhBnL",
        "CVzDCPGMVqVmGsGGbJCmCDvMcRcqnBFFFnRBBNRBBNqhnFfF",
        "DsmSGsGPzvMGJvdbgTSTbjbSSdgH",
        "jBGmbNBQGdBNNDJNQRLLVDsHtDRzHHZZcH",
        "wCWPFWPCrPhPrplvprhwpCHHtszttqZslRVHLtzVlJZL",
        "vprMMvMnJCwnnPShNGSTfGSfNmmgdNff",
        "bPtLbvVWWztbLSVVnbszpzQsrcDDBdpRcDrs",
        "llZmgCZqgCFgmdRdJcscBdJsmQ",
        "FZlgfqCFfgZHlqCMCglwCFGWntLLSMRSPGPVttWRtVGL",
        "vtnDsDtrnrSvrMVmbrrJgPCmBm",
        "FpQHzFclLVzWHhwHLQLlHLzPmMBQCJTdTmCTmBTJTTmgQg",
        "pllcVWqlffZqZtZD",
        "TSSZWpsQmZWcTZSvsTTTppNPzrBPrNBrzQNVFrBBNPqP",
        "CgjmCbtGgftMmLtLmffzBzJJJNVVMNzNBqJrFN",
        "gjgjLgtLwgbGjHdhhGdvmlnllnpWnplZvcvwTl",
        "htLrRFRtbbhlGSLRtbJBJsjBmgMMgJgtmBzz",
        "pZQWddQQfpZZffcDQZwddQwDMqDDsPgGJJzzjqzgJMBJgmms",
        "QdcQTdwpGNwfrCRlRVlNLSbb",
        "wrdvpVBVpMGPPjWjGZJJZT",
        "tChCSlNfCCHtvHHWPHPZ",
        "RbRRNvmcqcblfMwwdVBQQqqdpL",
        "qcctqRcqmcHWzHBdDMZhfwthBnwt",
        "JFsSNMSgNSNJJMGJBBdjhFDfhwhBrwnZ",
        "TbgbsSgJMTJllblLCSPlsTCVQmRVVWpQzzqpqzVzHLQzcc",
        "CVcWbjjSSCSSnpjWpCpprhHZlHtHGzHrZrHGclrl",
        "gqZqdddLgmgNqvTGGHvvmrrGHT",
        "FFDgZfZNLMgNfdDqDRnsnjBpbSbnMBBWpQpB",
        "qwpQFwRnqFFfSBSfFt",
        "LJJLGLWWtZlbgWHgGshhSdSVzmhHmfVzzC",
        "lrbrbrNNJgDMLLbblGctvvvDqPcqctTTTcqP",
        "vnblvbfHvlcHMlHlZbSPLTPLwCMBRRPRRFFR",
        "tszzBqtzDsWVPRSmzLVmVL",
        "tsNsDDNgGsqBrgBpgdHQbfhflcHdpZvdbh",
        "cCpLtpGGLsgsppcpmGGHMtjfHRVhvvVVFRfhjV",
        "NWnnnNNndQnQZdCdzzRVMHzvhhHWWWjj",
        "CPJJrnSZpGDJLGTL",
        "cnJzpcnmnQVFbzTlvTHBlb",
        "tWCDPjfsDGfZhddhjjdTvFTgFgvbnFHvdHqT",
        "hjfCjwDDGjPthsfhsnGNrJcQcRmJMLVJrJNMLw",
        "CPPRrSlRccPcwTHwfdwTHdfl",
        "mLQLLjhQhhQLZvpzssHDhdTswzzTJD",
        "gmjbBvQLWmgbQZBCSRnnnSMVCBHnBS",
        "sWrBJbsVqschzhQzHh",
        "gtFmztnSlSfdlmnZSdSwcwGRTjcTcwwTcHccRg",
        "FzFDzMZCdDZtCSrJVBMqWVrqNBqN",
        "TvWlhhfhZJVgtSSl",
        "ddBdGGdFmmBbdzqqPDDGGmdDZSgttHtZppSgzZHSgMhtMgtz",
        "PGqdrbbbdPnrcjjhTRWLLc",
        "trrmJWcrVwVbcPScdcBdGPHH",
        "JTQnfjlJTpQFfMLlNJHHGDPdGsSdDjHGDPPH",
        "ffFfnCTTCfTlplTMvNVzqWvwVzrrhwmWhJbW",
        "hVtDtgcghzJpmmhlwp",
        "srsnrqqsPqsBPvnqRBRMPbnwlplpmCStJwmzJPtJzJfwSw",
        "bbrqjBbvGsjGGBWqMVFFVDNVNjZjgtgFgZ",
        "mnmhBDHhwWCHsTgRsH",
        "dcSlFvccMFMMFFggNsTzzvvzWnVW",
        "llQdllZScFplJPpdcZSqBqjhmtnrwrDGnQGhrq",
        "ZffVNgfTdmPVltsnnGwgQDnB",
        "rMCFLMHpzCMFzHpzbrcHFLzBwsDsDDnlDBJrDDBBSJSnBn",
        "MLMjMzqpCzvwqTmwZdvq",
        "DDNlWPRqgPRPsRFjJQZbchJZbgQJ",
        "zzrLLznpLbHnjcBHvVvHvJcZ",
        "ndmrTzbMMTfzrTfnTLrzdpmsPPPqlqGDNNsPCRDRqRsD",
        "zzdqTNfTfdfhgQhgqMFSjRDtDRWHqtWlwtqDRS",
        "ssBCrcmpVGZvVRDdSDRwtmWdDb",
        "rvGPCZLCVCPVBZFdnfThgNgLJNhf",
        "bslcrssQwDPbQrrcsbsnQrjMLthPMMRhLRhLRgzmgPhRgM",
        "DffvDfHGfNFdpfTdMtghLBThzVmBhBtM",
        "SNvJNJdflDDbcDWJ",
        "HFlHNpWsTlGWbFsGFTGHFLLNzPPhLVPMzVzMNPhhzP",
        "jSvZtmrqqpcrCpPVzw",
        "dddQvqDgDmjdSQQdqZjStpffWGgBRWTGfGsRlWBlHF",
        "THnTbNrdBnLTHHnTnBrWRTndsccZsLZcDqmLDPcDlQDsmmsZ",
        "ptwzzhpvGSVdqQlmszqmqPqc",
        "wGVjSddCBggCHFWN",
        "LFFbdbhhhvwvfTNdRhhRRvMbHDGjcfcGfDjtDHHcHqGjDqqj",
        "WlQnVpWSSWWsPsgDqDzHDLHjJcttGP",
        "rrWsZrgVnWrWSlmSlmSBFFbvTThhBFvvZLBhRw",
        "BgBdcjThvjFcTggrqvVfzlnnPlrqLt",
        "JpwJGPsQwpwSssHpPLlzlnNlzLLNNLVtsN",
        "JPMmWGmWPmHbHpJbWGJmDmwbBTRZMBBdZCRTRjFjhCZCCBTT",
        "BjbcLFRfBRhnbGjCVVvPllpcPtcDmdlPpvPP",
        "WrMQqCNgsqWWsTNCMZMWWsWPvJDJDddvlpDtZDpDDDDwvP",
        "qNMzzSzSQsGLbFCSCnVR",
        "tTRpHJQpQBZcddhhMhvhJN",
        "zswljflgMFbwPqmNmSdvShLNfLhm",
        "qFbsMCVgsqMwRWHCWDDBDWpt",
        "VSTCCWsJvGpHHCNC",
        "GrqzZrrZjDljcDDlfjMqgRPfPvQPpBHNvHvBpvNQ",
        "rljncDcznjMqhlhZDnltrzhTsGWtbVLFTTWGsbdWJdFTmL",
        "mJPDSJJPZPJNrprSNrDmpZGrhFFhBqjGbGGVbFjhhfqBjBRV",
        "cgnTQHdMQdTHdhqfggBhVqVfVS",
        "nQdLLddssSJrmsNvZrPz",
        "jfjffQzZQQMzZZfZZQFgjDWBCRlCBdTTBGGGRpBCgdhdBG",
        "LrstWtNsbHLsprRBdlGpCwlh",
        "HLnntbnscqLvvPNNfMWSSmDMDPjzjDzS",
        "vhcGwWVvglltcfBn",
        "BBSLrzSJLzJNJrLfPfPRsmDRmflD",
        "jMjFZJNMqzrzZzFNFjNQqJzbCpBBvWdpvTCWhpVwdvHVCGbG",
        "HlrnFmRmtRBQPVBTQHHQ",
        "psSLJsLpTTdPdLTv",
        "fCGgTgfSSCtRtFFzql",
        "pfTpStppcDlWfbpDdzQRsQGJhfffQgJHzN",
        "ZFZFZmBFwVwBVmLmLsRLRhHNzRLRNNzJ",
        "FnnjwVPmnqqqjBjrTdblldCTpcPJtbTD",
        "bdZHdWlrjslMMwGG",
        "rDDTRBTqSqmJLBJRBTSJpmMsMMjhwvfMhjjfVGsLshhC",
        "BqQFRPFRQBJgzrcZNHFdZt",
        "wrDdLlDdPWZPTTrwlZpSsPsHVHsSCHnbzMHM",
        "JtNFttNCjFvpppnMpJgSVS",
        "NFFqFcCQCvfrZmGdZdmqrW",
        "GMNNfJnNddJFJWsv",
        "HSDwCmmghLmwmmHDpsvdFpMWpppptSbp",
        "zCzBCgzhwmhzLrPnVrMqZBNfGf",
        "DrHGtbltbCjjjffPrgsmzmcqsgDczdsmgJ",
        "VZLwQLZLLVwLBQZnLVphhLQQqsTNmzJdcNTzzmJNqlNBsszz",
        "wZLhVMplpQVRRlpVGPfjCjMGCrbHGWWb",
        "BHpFrHHbBNTWWTWNhCPwPLNPjCdjLV",
        "zJRRzJvZlcZsSMJdzSDjDtfDCtDtjDjjjj",
        "dcJcszQJJGRJzRllMpGHpFTWmrTmBTbWWB",
        "qnWWqhDhnjmjCMBlNRrfVfRNCB",
        "vvBLBtGHJTHBddrNVJrVSVdr",
        "BZLTHbgvHvTFBgTFFvhmWmmZDPmmZDsnqncs",
        "WBvmjDbSzTMmHHdpNHNF",
        "ttlflZRfGtfWVRltGtflCdHnJrNJHNHnJddNMNCnpF",
        "VVwssWQQfRGZcszBQzDbjSBvSBDP",
        "lSlQqQVqWWVWfqQWVJSTscdmPPwwTTmjjfpjPp",
        "FCbzHbvHvtgrtFCvbvbbwdTwmsrwnTTpmdswmwcc",
        "DtZbHdghztlLMQlWWhVQ",
        "pqzzFSmdFqbQvlpdDGGrGBWPPBVNQnVttZ",
        "cgcjwfBMhHCjjLMCrtcnPcsnsPGVnrVs",
        "JgCChjjjBHhRRLLjjhplzvzpSFJvzzlDbSqm",
        "mZzVQZMhmrffwfQhWhzmrmpBtRcdbnbcdcMpBbDbncdD",
        "jsLTSlTWRBSDpnDn",
        "GLTsGWGFsfmJGZVJZm",
        "BGWshBGnsFWSLWBLlSSLWRJHnrVPrPcNHCNHctnPPJ",
        "QmvQCqqMTZqvgmvTjpZCMgMtrVctPptHtrNVrptbJJbrRP",
        "CzjCZfCwDzShDWdF",
        "HmQlQHmJnpmptmzt",
        "MTqMjMPvTvVvhpdztZnSwzwZqS",
        "CcbLLPTMtCCsjHNHQFLRRFlRNN",
        "GDFwLLLLSrbdPlFBMFsslFHmZH",
        "TnJCgthHpVTfZMQZQmzWnZ",
        "hjvtjtghtqJvVjhTgNhJTvdvdDDRbbccrwPdcGwrHS",
        "MQQMBPzMGQBPBbDQPMhpnRwsGnRhNrFFpRnF",
        "vmgHcmCTTlvvvZvTmqcTfmCRdddFnwdRdnVwFpVfpRnwNw",
        "gvmqJTcHclCQJNzjMLWbLj",
        "DbqqDDbQFqfNtZSLSq",
        "RrdjPdmrpWBdmWRdccfLtNttSDMZBfftLMLf",
        "dCcgmgRrWcgcppjCVVVVFHFnDnbJnb",
        "fZMFfrtVdZSDVwTgjRMLhwTCLj",
        "cNzPBNpclllzHbmTNRhqCRTgjC",
        "nhhWJzhGPlQcGvsvfJtSfZfrtt",
        "PSzrBWQBBGzBlnSnWtDrqHfNfwVwHcLNjHjwcDNmFH",
        "hbRhtRCRpRvsRgVVVcNHNNNCwLwc",
        "ZtRTRvttWWzBPlGZ",
        "tcLnctNsJrWWNDTN",
        "pwPPSjHSHHfzvmSvvvFVVGqGVqGmFqrDWgDr",
        "pPSvfPQMzCQCSbhllLnQDhbtQZ",
        "DmLffDhpVhjjVwvbwNVFbbNSNH",
        "JRPBgMPRHBrMHMHqrBMqWJBSQQNbCvndNrdvCNCFwFrQnv",
        "WcqJcPGMGtWRRBtgZjjspGHTLHGHTppm",
        "ptJtWJpqRwDZZDVWpbDWqlvvflfMjlfCMjdCCdtslv",
        "rLwTBGBzBBQTzmwCCjvdvlLllddsMl",
        "NBwTmrGNgrTrcgPpWgWPDSVVPW",
        "CdglMnrlSSqDPpcsZb",
        "ccwmVJtvVvVtNhBpBFPDVpqbbD",
        "TRGQjJjGTmtrTCgHWLfrcn",
        "JNNhLwWwWQHNPDmmjHpc",
        "zMqZCvVCSMVqMSTVvZVGsBnlslpmsmzlPmsHPsPB",
        "qTVqrgdCCbhfHJQFtg",
        "wNwCBBCZsfQWfmLCGSmmFRGSSF",
        "zjnPHPVqMhhZLTcbpbSncp",
        "lVlhlgzlPZlwtgBddJdfvf",
        "JWRWRRLWJLnjtjnLzGzznflBvfPvPMqMDqdbzblCzC",
        "TTScTVbHmTsVFrmcsgcHFlPMMvlvrDPdlrDDqdldvl",
        "bVpcpchgsFZHbhSmSTsHFFjwtZjnjLttntNjLjNLWtjw",
        "rffjPJzWzrgPpGWHVNqTtmqFTVRH",
        "cswhvlLBvSLsCtbFccmqVFNTbb",
        "wwZSCZSnCLsSDGgDmpGnfmmr",
        "rTfJTNtjfNljlrWSlzRtNlTqsddwGnsnHHwwhssTsnqw",
        "VpbpZZbvPLbZbbBhwqMHhsGMnJdVwV",
        "mgQZJDLBJbbbcbgZClCSfWlrCjRjlDCR",
        "fSpwcVfzsztcSSWNNMbnMRqTvtTv",
        "mJFmGDDDhGhBJHCQddllqTvCllqTRRWNnMbT",
        "FdFDGdDDDhhHdZDjhDmpwSPVZszpwZsVgsPRZs",
    ];
    task1(&input);
    task2(&input);
}
